name: Debricked SCA

on: [push]

jobs:
  debricked:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Fingerprint files
        run: |
          dotnet restore --packages nuget/dvcsharp-api-master/packages
          debricked fingerprint
          
      - name: Run Scan
        run: |
          debricked scan
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

      - name: Run Scan review
        if: success() || failure()
        run: |
          debricked scan --no-fingerprint
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN_REVIEW }}
          DEBRICKED_URI: 'https://review-0-prevent-jw9h9c.review.debricked.dev'

